trigger:
  - main  # Запуск конвейера при изменении ветки main

pool:
  vmImage: 'ubuntu-latest'  # Используем виртуальную машину Ubuntu

steps:
  # Установка Node.js
  - script: |
      curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt-get install -y nodejs
      node -v
      npm -v
    displayName: 'Install Node.js'

  # Установка Newman для выполнения тестов Postman
  - script: |
      npm install -g newman
    displayName: 'Install Newman'

  # Запуск Postman коллекции с генерацией HTML-отчета
  - script: |
      newman run postman-tests/BerlinTravelAgencyTests.postman_collection.json \
        -e postman-tests/BerlinTravelAgentcy.postman_environment.json \
        --reporters cli,html,junit \
        --reporter-html-export postman-tests/newman-report.html \
        --reporter-junit-export postman-tests/newman-results.xml
    displayName: 'Run Postman API tests and generate reports'

  # Публикация JUnit-результатов Newman
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'postman-tests/newman-results.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish Newman Test Results'

  # Публикация HTML-отчета Newman как артефакта
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'postman-tests/newman-report.html'
      artifact: 'Newman Report'
      publishLocation: 'pipeline'
    displayName: 'Publish Newman HTML Report'