trigger:
  - main  # Запуск конвейера при изменениях в ветке main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Явный шаг для клонирования репозитория
  - checkout: self
    fetchDepth: 1  # Извлечение только последнего коммита

  # Установка Node.js
  - script: |
      curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt-get install -y nodejs
      node -v
      npm -v
    displayName: 'Install Node.js'

  # Установка Newman
  - script: |
      npm install -g newman
    displayName: 'Install Newman'

  # Запуск Postman коллекции
  - script: |
      newman run postman-tests/BerlinTravelAgencyTests.postman_collection.json \
        -e postman-tests/BerlinTravelAgentcy.postman_environment.json \
        --reporters cli,html \
        --reporter-html-export postman-tests/newman-report.html
    displayName: 'Run Postman Collection'

  # Публикация HTML-отчёта Newman как артефакта
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'postman-tests/newman-report.html'
      artifact: 'Newman Report'
      publishLocation: 'pipeline'
    displayName: 'Publish Newman Report'